#
# Testcase for root/cimv2:RCP_ClassMethod
#
# Generated by 'genprovider' for use with cmpi-bindings-ruby
require 'rubygems'
require 'sfcc'
require 'test/unit'

class Test_RCP_ClassMethod < Test::Unit::TestCase
  def setup
    @client = Sfcc::Cim::Client.connect(:uri => 'https://wsman:secret@localhost:5989', :verify => false)
    @op = Sfcc::Cim::ObjectPath.new('root/cimv2', 'RCP_ClassMethod', @client)
    assert @op.client
    assert_equal @client, @op.client
  end
  
  def test_registered
    cimclass = @client.get_class(@op)
    assert cimclass
  end
  
  
  def test_method_Classname
    assert_equal "RCP_ClassMethod", @op.Classname()
  end
  
end
