#
# mkregistration.rb
#

def mkregistration c, namespace, providername, out
  out.comment.comment "Registration for provider #{providername} of class #{c.name}"
  out.comment.comment "Generated by 'genprovider' for use with cmpi-bindings-ruby"
  out.comment.comment "Classname - Namespace - Providername - Libraryname - Capabilities ..."

  capabilities = ""
  capabilities << " instance" if c.instance?
  capabilities << " method" if c.method?
  capabilities << " association" if c.association?
  capabilities << " indication" if c.indication?

  out.puts "#{c.name} #{namespace} #{providername} rbCmpiProvider#{capabilities}"

end

