[ Description ("A dummy class to represent array data types" ) 
]
class RCP_ArrayDataTypes
{
  [Key]
  string Name;
  
  boolean bool[];
  
  string text[];
  char16 wchar[];
  
  uint8  unsigned_char_8[];
  uint16 unsigned_char_16[];
  uint32 unsigned_char_32[];
  uint64 unsigned_char_64[];
  
  sint8  byte[];
  sint16 short[];
  sint32 int[];
  sint64 long[];
  
  real32 float[];
  real64 double[];

  datetime date_time[];
};
