//
// trivial.mof - A trivial sample file for genprovider
//
//

#pragma locale ("en_US")
//#pragma namespace ("root/cimv2")

Qualifier Provider : string = null, 
    Scope(any);
Qualifier Description : string = null, 
    Scope(any), 
    Flavor(EnableOverride, ToSubclass, Translatable);
Qualifier Key : boolean = false, 
    Scope(property, reference), 
    Flavor(DisableOverride, ToSubclass);
	
// ===================================================================
// 	Cmpi_Swig
// ===================================================================

[ Provider("cmpi:cmpi_swig"),
  Description ("A sample class to demonstrate cmpi/swig" )
]
class Cmpi_Swig : CIM_ManagedElement
{ 
  [Key, Description ("A friendly greeting") ]
  string hello;
};
