//
// trivial.mof - A trivial sample file for genprovider
//
//

#pragma locale ("en_US")
//#pragma namespace ("root/cimv2")

// ===================================================================
// 	Cmpi_Swig
// ===================================================================

[ Provider("cmpi:Cmpi_Swig"),
  Description ("A sample class to demonstrate cmpi/swig" )
]
class Cmpi_Swig : CIM_ManagedElement
{ 
  [Key, Description ("A friendly greeting") ]
  string hello;
};
