#
# registration.rb
#

module Genprovider
  class Registration
    def initialize c, namespace, providername, out
      out.comment.comment "Registration for provider #{providername} of class #{c.class}"
      out.comment.comment "Generated by 'genprovider' for use with cmpi-bindings-ruby"
      out.comment.comment "Classname - Namespace - Providername - Libraryname - Capabilities ..."

      mask = Genprovider.classmask c
      capabilities = ""
      if (mask & ASSOCIATION_MASK) != 0
        capabilities << " association"
        # an association provider is also an instance provider
        mask |= INSTANCE_MASK
      end
      capabilities << " instance" if (mask & INSTANCE_MASK) != 0
      capabilities << " method" if (mask & METHOD_MASK) != 0
      capabilities << " indication" if (mask & INDICATION_MASK) != 0

      out.puts "#{c.name} #{namespace} #{providername} rbCmpiProvider#{capabilities}"
    end
  end
end